- name: Configure OSPF for DLS1
  exos_config:
    lines:
      - configure ospf routerid 1.1.1.1 
      - configure ospf add vlan Accounting area 0.0.0.0 
      - configure ospf add vlan DMZ area 0.0.0.0 
      - configure ospf add vlan Native area 0.0.0.0 
      - configure ospf add vlan Printers area 0.0.0.0 
      - configure ospf add vlan toFW area 0.0.0.0 
      - configure ospf add vlan User_Workstation area 0.0.0.0 
      - configure ospf add vlan Wifi area 0.0.0.0
      - enable ospf
  when: ansible_network_os == "community.network.exos" and inventory_hostname == "DLS1" 

- name: Configuring OSPF for Firewall
  fortios_router_ospf:
    vdom: "{{ vdom }}"
    router_ospf: 
      router_id: "2.2.2.2"
      area:
       - 
        id: "0.0.0.0"
        authentication: "none"
        type: "regular"

      network:
         -
            area: "0.0.0.0"
            id:  "65"
            prefix: "172.16.1.0/255.255.255.252"

      ospf_interface:
       -
        authentication: "none"
        name: "port12"
        interface: "port12" 
        hello_interval: "10"
        dead_interval: "40"
        network_type: "broadcast"
        status: "enable"
      default_information_originate: "always"
  when: ansible_network_os == "fortinet.fortios.fortios" and inventory_hostname == "NGFW"
